### ISSUE TITLE
How do I know which version to add to build.gradle

### ISSUE THREAD

**Issue by talmaoz** [Nexmo/verify-android-sdk#11]
Hi,

I am using Android Studio, trying to integrate Nexmo into my app.

In the instructions, it says to add the following to my build.gradle:
dependencies {
compile 'com.nexmo.sdk:verify:<RELEASE version number>'
}

But I can't seem to find what to replace "<RELEASE version number>" with...

Can you help or direct to the proper forum to ask this question.

Thanks a lot :)

**Comment by emmaChristine** [comment]
Hello
Please use the latest version on maven central, which is 1.0.1
http://search.maven.org/#artifactdetails%7Ccom.nexmo%7Cverify%7C1.0.1%7Caar
If you have any other questions please check the official docs on
https://docs.nexmo.com/libraries/verify-sdk/verify-sdk-for-android or just
drop us an email in here.

Best regards
Emma

**Comment by emmaChristine** [comment]
Verify SDK has been updated, newest version is 'com.nexmo:verify:4.0.0'

Note:
As an alternative to checking the dependency version on Maven central, as of Android Studio 2.2, a new Project Structure dialog shows the list of dependencies your app is using with the available updates from local AND remote repositories as well.

Activate it by going to "Android Studio > Preferences > Build, Execution, Deployment > Gradle > Experimental" and check the 'Use new Project Structure dialog' 
Then open it by going to "File > Project Structure > Messages"

Kind regards,
Emma
