### ISSUE TITLE
Duplicate permissions

### ISSUE THREAD

**Issue by antonpit** [Nexmo/verify-android-sdk#13]
Hi,
In a SDK manifest declarated pemission :

<permission   android:name="com.example.gcm.permission.C2D_MESSAGE"
        android:protectionLevel="signature"/>
    <uses-permission android:name="com.example.gcm.permission.C2D_MESSAGE"/>

If user have in his phone app that use VerifySDK then on update or install another app with sdk Google play throw an 505 error and not complete the installation/update until remove the first app.

It means user could not install 2 or more apps that use the SDK.

Thank you.

**Comment by antonpit** [comment]
I mean user permissions then start with "com.example..."

```
<uses-permission android:name="com.example.gcm.permission.C2D
```

**Comment by lolobosse** [comment]
I confirm the bug, it is pretty much critical for companies using many versions and flavours
