### ISSUE TITLE
UNEXPECTED TOP-LEVEL ERROR

### ISSUE THREAD

**Issue by rjain90** [Nexmo/verify-android-sdk#16]
Getting the following error when I try to run the app after adding the verify dependency to the project

```
Error:UNEXPECTED TOP-LEVEL ERROR:
Error:java.lang.OutOfMemoryError: GC overhead limit exceeded
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
Error:com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
Error:com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
Error:java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
Error:java.lang.UnsupportedOperationException
```

**Comment by emmaChristine** [comment]
Hi,
We have just published a new version of Verify SDK, please feel free to update the dependency:
'com.nexmo:verify:4.0.0'. The main update is added Firebase push notifications support, to replace GCM.
We weren't able to reproduce your issue, but please let us know if the problem persists.

There is a sample app which includes Firebase support:
https://github.com/Nexmo/verify-android-sdk/tree/verify4.0.0/VerifySample_PushEnabled
Please feel free to check it out as a starting point.

Kind regards,
Emma

**Comment by wrousseau** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UNEXPECTED TOP-LEVEL ERROR](https://trello.com/c/S9ybRR1S/9-unexpected-top-level-error)
