### ISSUE TITLE
GCM support

### ISSUE THREAD

**Issue by zackd** [Nexmo/verify-android-sdk#17]
GCM is now deprecated, see: https://developers.google.com/cloud-messaging/android/client

also GCM version is hardcoded: https://github.com/Nexmo/verify-android-sdk/blob/verify3.0.0/verifySDK/build.gradle#L54
- do I need to downgrade my project libs in order to use the SDK? I get version mismatch error "all com.google.android.gms libraries must use the exact same version specification."
 
what about support for firebase ?
my project uses firebase messaging - do I need to downgrade to GCM to use the SDK?

**Comment by emmaChristine** [comment]
Hi Zack,
thanks for getting in touch.
We have just started working on a migration towards Firebase, we will update this thread as soon as a new release is available.
The library had to use certain dependency versionns, as publishing a lib to Maven central rejects any dynamic dependencies. So we won't be upgrading to a new gcm version anymore, and just go with Firebase.

Cheers,
Emma Tresanszki

**Comment by emmaChristine** [comment]
Hi Zack,
thank you for your patience, the verify SDK has been updated now, please update your dependency: 'com.nexmo:verify:4.0.0'

There is a sample app which includes Firebase support:
https://github.com/Nexmo/verify-android-sdk/tree/verify4.0.0/VerifySample_PushEnabled
Please feel free to check it out as a starting point.

Many thanks,
Emma

**Comment by zackd** [comment]
Thanks Emma, 

having some issues with proguard, but can't find any documentation re: proguard for the verify sdk. Could you share proguard-rules.pro in https://github.com/Nexmo/verify-android-sdk/tree/verify4.0.0/VerifySample_PushEnabled ?
.. I notice that file is ignored here: https://github.com/Nexmo/verify-android-sdk/blob/master/VerifySample_PushEnabled/app/.gitignore

this is what I have so far for nexmo-verify-sdk:

```
# nexmo-verify-sdk
# uses org.apache.http.legacy:
-keep class org.apache.http.** { *; }
-keep class org.apache.commons.codec.** { *; }
-keep class org.apache.commons.logging.** { *; }
-keep class android.net.compatibility.** { *; }
-keep class android.net.http.** { *; }
-dontwarn org.apache.http.**
-dontwarn android.webkit.**
```
