### ISSUE TITLE
Missing or Invalid app_id

### ISSUE THREAD

**Issue by duranmla** [Nexmo/verify-android-sdk#18]
I'm just getting the samples and replace the values of `NexmoAppId` and `NexmoSharedSecretKey` with their values on my dashboard at:

![verify__sdk_your_apps](https://cloud.githubusercontent.com/assets/1425162/20193600/1b21e1f6-a765-11e6-99de-6aa3325d4f8e.jpg)

I'm just copying and pasting those values but I still getting:

![config_java_-_verifyquicksample_-____mobile_android_verify-android-sdk_verifyquicksample_](https://cloud.githubusercontent.com/assets/1425162/20193550/c883ef70-a764-11e6-9939-c2969f066f50.jpg)

Keep in mind that I'm using the Nexmo service with node, and it is working making the request manually (using master keys), so it is not something like: "My apps doesn't are not enabled or something like that"

Any thoughts?

> I'm testing with Venezuelan phone number, Android OS 6, HTC M8 (if that provides some help)

**Comment by duranmla** [comment]
The issue was the line:

```
.environmentHost("https://test.nexmoinc.net/sdk/")
```

That is on the creation of the nexmo client on the examples, after remove this line, everything work as expected.

**Comment by emmaChristine** [comment]
Hello Duran,
Thank you for getting to the bottom of this issue.
It was a mistake from our side, having forgotten the internal endpoint, we shall remove it from the samples now.

Happy coding,
Emma
