### ISSUE TITLE
Error trying to integrate the SDK under applications that run Android 4.4.4

### ISSUE THREAD

**Issue by duranmla** [Nexmo/verify-android-sdk#19]
I have two physical phones one with Android 5.0 and another one with Android OS 5.0, however, the application that I'm currently developing need to have support from API level 18, which include Android OS 4.4.4 The problem is: When I install the application on devices with 4.4.4 the application crash I have test it on my emulator and I have a team mate with the same issue on a physical device with 4.4.4

After track down the issue the bug arise when I just simply include:

```
compile 'com.nexmo:verify:3.0.0'
```

Getting logs like: https://gist.github.com/duranmla/47a14a1a9da939275ac9dbe39ff10874

**Comment by zackd** [comment]
.. looks like the documentation has not been updated for version 3.0.0 - you might have more success with version 2.0.0

https://docs.nexmo.com/verify/verify-sdk-for-android/integration

**Comment by duranmla** [comment]
Thanks @zackd ,however, my issue was a conflict with `com.googlecode.libphonenumber` dependency that I'm using, somehow, the version that I was using make some conflicts with nexmo sdk, in that sense, I updated the version of `com.googlecode.libphonenumber` (carrier and libphonenumber, in my case) to the latest one until now and that solves the problem.
