### ISSUE TITLE
change sender id in android sdk

### ISSUE THREAD

**Issue by noam2** [Nexmo/verify-android-sdk#20]
hi
is it possible to change the sender id from verify to something else , like its possible in your official api ?
and what about the body as well ?

**Comment by wrousseau** [comment]
Hi @noam2,

Could you confirm you are talking about the `sender_id` from the table in https://docs.nexmo.com/verify/api-reference/api-reference#vrequest and not a sender_id for gcm? What do you mean by body?

If you could show us what part of the doc you're looking at, it would be helpful :)

Cheers

**Comment by noam2** [comment]
i'm talking about sender id from the android SDK, not the official API. 
https://docs.nexmo.com/verify/verify-sdk-for-android/prerequisites
this github library is about that
