### ISSUE TITLE
Getting error while adding sdk with my android project.

### ISSUE THREAD

**Issue by mbrk1234** [Nexmo/verify-android-sdk#21]
Hi I am getting error while i am adding sdk.
Error:(120, 0) Could not get unknown property 'GROUP' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

**Comment by emmaChristine** [comment]
Hi,
Can you please give us more info on how you have added the SDK to your project?
Are you using latest sdk dependency, or did you include the module manually?

Best regards,
Emma
