### ISSUE TITLE
Failure to work on Android O

### ISSUE THREAD

**Issue by IanWambai** [Nexmo/verify-android-sdk#23]
On Android O devices, the VerifyClientListener gives the error OS_NOT_SUPPORTED when trying to verify.

**Comment by emmaChristine** [comment]
Hello Ian,
Thanks for reaching out, our service hasn't been updated yet to accept new beta versions.
We'll update this thread as soon as this happens.

Cheers!
Emma
In the meantime, can you please send us your api key, just to double check if your device Build.VERSION is "O"?

**Comment by IanWambai** [comment]
I sent it when I created the support ticket.

**Comment by IanWambai** [comment]
Question: Can you please provide a timeline as to when this might be fixed?

**Comment by emmaChristine** [comment]
We anticipate for end of next week, but we'll keep you posted.

Cheers!

**Comment by emmaChristine** [comment]
Hi there, we have deployed the change on our backend, so feel free to give it a spin!

**Comment by IanWambai** [comment]
It work. Great :-)
