### ISSUE TITLE
Getting Missing or Invalid 'source_ip_address'

### ISSUE THREAD

**Issue by blastering66** [Nexmo/verify-android-sdk#24]
Hi, im already add new appliaction in Nexmo dashboard.

app id, and secret key is Correct.
BUT when im build the client. and request 

im getting response : 
`VERIFY raw response: Signature: 6d34e0562e008a33485cda8f778389f0. Content: {
                                                      "result_code": 51,
                                                      "result_message": "Missing or Invalid 'source_ip_address'",
                                                      "timestamp": "1501241515"
                                                  }`

this is my code : 

`verifyClient.getUserStatus(COUNTRY_CODE, PHONE_NUM, new SearchListener() {
            @Override
            public void onUserStatus(UserStatus userStatus) {
                Toasty.info(getApplicationContext(), userStatus.toString()).show();

                if (userStatus != UserStatus.USER_VERIFIED){
                    Log.e(GlobalVar.LOG_INIT_TAG, "Verifying to SERVER");
                    verifyClient.getVerifiedUser(COUNTRY_CODE, PHONE_NUM);
                }
            }

            @Override
            public void onError(VerifyError errorCode, String errorMessage) {
                Toasty.error(getApplicationContext(), errorMessage).show();
            }

            @Override
            public void onException(IOException exception) {
                Toasty.error(getApplicationContext(), exception.getMessage().toString()).show();
            }
        });`

Can u tell me whats wrong ?

My number didnt get The Verification SMS

**Comment by emmaChristine** [comment]
Hello,
to make sure you can perform any request towards Verify SDK Service, 'android.permission.ACCESS_WIFI_STATE' has to be granted by your application (it's because IP_ADDRESS of the device is used internally)

Can you double check that your app has this permission Granted?

Thanks,
Emma

This is the list of all permissions required: https://docs.nexmo.com/verify/verify-sdk-for-android/integration
